### ISSUE TITLE
Reference list of missing issues for use cases and capabilities

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#110]
In the hope of potentially saving you guys some time, I've been going through the spec for use cases and capabilities that do not link to an issue for discussion, and I've also tried to find the corresponding issue in any case there is one but it just hasn't been linked to from the spec.

<hr>

Edit: Things TBD  as listed below have been updated to reflect changes in:
https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/commit/0071b30625a29455ea3e4105aefce4e3eff5e755, https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/commit/ae59ecb6e8a85acbf21489916079a5afa2d398ae, https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/121/commits/6826d37de02e51d5e1b92089696e01846f5fa7d8, https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/124, https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/162.

<hr>

These [examples](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/tree/master/examples) have broken links to corresponding use cases in the spec:

- [ ] [animate-view-change.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/animate-view-change.html)
- [ ] [change-bearing-map.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/change-bearing-map.html)
- [ ] [create-plugin-integrates-api.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/create-plugin-integrates-api.html)
- [ ] [custom-map.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/custom-map.html)
- [ ] [generate-vector-features.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/generate-vector-features.html)
- [ ] [heatmap.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/heatmap.html)
- [ ] [reset-map-view.html](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/reset-map-view.html)
- [ ] [set-layer-visibility.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/set-layer-visibility.html)
- [ ] [specify-data-source-map.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/specify-data-source-map.html)
- [ ] [set-view-zoom.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/set-view-zoom.html)
- [ ] [view-change-events.html](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/examples/view-change-events.html)

<hr>

These issues aren't properly linking to their corresponding section in the spec, e.g.:

> _This issue is for discussion of &lt;link&gt;._

is missing, or have a broken link:

Items in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/110#issuecomment-529998014

<hr>

<s>These use cases and capabilities are currently not linking to a corresponding github issue (perhaps because no such issue exist yet):</s>

- [x] 25 items complete, in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/162.

**Comment by AmeliaBR** [comment]
Yes, this is the intention. It has been on my To-do for a while to go through & find the missing cross-links. So thank you for the reference list! I will try to get to these this week.

**Comment by Malvoz** [comment]
Additionally, all issues on [use cases](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues?q=is%3Aissue+is%3Aopen+label%3A%22discussion%3A+use+case%22) and [capabilities](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/labels/discussion%3A%20capability) point to the corresponding section in the spec - I've found that some of these links aren't working.

Another thing would be to make sure the [examples](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/tree/master/examples) link back correctly as well.

**Comment by Malvoz** [comment]
@AmeliaBR I've updated the lists above since https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/commit/0071b30625a29455ea3e4105aefce4e3eff5e755, and regarding the (new) examples that link back to use cases, many of them are broken because they don't include some delimiters while the `id`s for the use case sections do. For example:

The [show-vector-data-overlay-map.html](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/show-vector-data-overlay-map.html) example links to [`#use-case-show-vector-data-overlay-map`](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/index.html#use-case-show-vector-data-overlay-map) while the id for that section is [`use-case-show-a-vector-data-overlay-on-a-map`](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/index.html#use-case-show-a-vector-data-overlay-on-a-map). Would you rather change the `id` in these cases or the links from the examples?

**Comment by AmeliaBR** [comment]
Thanks for the updates @Malvoz. Yes, I'm still working on going through the rest of the links; that commit was just the first batch.  But… it looks like I messed up in a few cases, by not including the `use-case-` prefix on the link back to the spec from the example page.  I'll review that.

I've also been simplifying the IDs as I go (to make it less likely that these little discrepancies will slip through), so for your example, probably both of those will end up changed!

Once I've done a full pass, I'll run the whole thing through a link checker & make sure we get this all tidied up.

**Comment by AmeliaBR** [comment]
OK, I *think* I've fixed the broken links and filled in the missing discussion issues for all the use-case sections (as of https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/commit/ae59ecb6e8a85acbf21489916079a5afa2d398ae).

Ran the main document through the W3C link checker, so at least I am sure that the links *out* of the report are OK. (Well, except for links to GitHub, since the link checker is blocked by robots.txt! But it's more likely that those are valid links but to the wrong issue rather than dead links, anyway!)

I still need to do another pass for editorial/content clean-up and standardizing the examples, so I'll double check the back-references (from the example files to the report) at that time.

Next step: missing issues for the capabilities section.
Also: avoid breaking things again as we fill in additional sections!

**Comment by Malvoz** [comment]
Thanks, I've updated the lists! :)

**Comment by Malvoz** [comment]
The list has been updated per changes in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/124.

**Comment by Malvoz** [comment]
> These use cases and capabilities are currently not linking to a corresponding github issue (perhaps because no such issue exist yet):

@AmeliaBR 

I'd like to open issues for all the cases where there is none yet, and also cross reference them from the spec afterwards. Is that okay with you?

I'm not permitted to label issues - so I could add a follow-up comment on which labels for you to set to save you time, then I'd delete those comments at any time you've set the corresponding label(s).

**Comment by AmeliaBR** [comment]
Hi @Malvoz, If you want to go ahead and make the rest of the missing discussion pages, I would be grateful. I haven't had nearly as much time & energy for this project as I'd like this past month, and your contributions are definitely appreciated.

I've granted you Triage permissions for the repo, so you should be able to add any labels as required. But if you're not sure about any of the details, just ping me in a comment.

**Comment by nchan0154** [comment]
Seconding the gratitude, @Malvoz! I have been meaning to go through these but I'm dealing with a bad case of RSI at the moment and repetitive clicking actions like making issues en-masse are difficult. Your assistance here would be much appreciated!

**Comment by Malvoz** [comment]
@AmeliaBR *"Take my energy ༼ つ ◕_◕ ༽つ"* 😄 

Thanks for allowing me to do this!

And thank you @nchan0154 for the kind words, too!

**Comment by AmeliaBR** [comment]
Whoosh!

I admit, I had one moment of panic when I saw the 30+ notification emails. Then I realized what they all were & “Hooray!”

Thanks again. It is very great to have those links ready before the big TPAC meeting, when we'll be trying to get new people looking at the report & starting discussions.

**Comment by Malvoz** [comment]
@AmeliaBR, @prushforth, @nchan0154, @NickFitz 
When you find that you have some time... (although this shouldn't take very long)

I think it's important (particularly for newcomers) that the issues for discussion properly link to their respective section in the report. Since refactoring some time ago, quite a few of the URLs have changed for certain sections of the report, thus they'll need to be updated - in some cases there is no link at all.

But this is all done below, so as issue owners you'll just have to edit the initial comment of each of those issues and copy/paste to include:

#### @AmeliaBR's

#### Issue [#12](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/12):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#mapbox">the reference tool "Mapbox GL JS API and Mapbox Studio embed"</a>.
<hr>
```

#### Issue [#13](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/13):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#d3-geo">the reference tool "D3 Geographies APIs"</a>.
<hr>
```

#### Issue [#26](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/26):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#openstreetmap">the reference tool "OpenStreetMap embeds"</a>.
<hr>
```

#### Issue [#27](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/27):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#bing-maps">the reference tool "Bing Maps embeds and Bing Maps Control API"</a>.
<hr>
```

#### Issue [#28](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/28):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#mapkit-js">the reference tool "MapKit JS (Apple Maps) API"</a>.
<hr>
```

#### Issue [#29](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/29):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#leaflet-js">the reference tool "Leaflet.js API"</a>.
<hr>
```

#### Issue [#30](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/30):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#openlayers">the reference tool "OpenLayers API"</a>.
<hr>
```

<hr>

#### @prushforth's

#### Issue [#3](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/3):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-reproject-maps">the map viewer capability "Reproject map tile data into a new projection or globe view"</a>.
<hr>
```



#### Issue [#9](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/9):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#google-maps">the reference tool "Google Maps embeds and Google Maps Platform API"</a>.
<hr>
```

#### Issue [#14](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/14):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-tile-coordinate-systems">the map viewer capability "Display map tiles defined in various common coordinate systems"</a>.
<hr>
```

#### Issue [#15](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/15):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-styled-features">the map viewer capability "Apply custom styling to map markers and vector features"</a>.
<hr>
```

#### Issue [#16](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/16):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-custom-controls">the map viewer capability "Toggle whether default controls are displayed"</a>.
<hr>
```
<hr>

#### @NickFitz's

#### Issue [#50](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/50):

```HTML
This issue is for general discussions of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#client-apis">the "Client-side Mapping API Capabilities"</a>.
<hr>
```

#### Issue [#55](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/55):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-create-initialise-and-display-a-map">the API capability "Create, initialise, and display a map"</a>.
<hr>
```

#### Issue [#57](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/57):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-implement-a-custom-control">the API capability "Implement a custom control"</a>.
<hr>
```

#### Issue [#74](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/74):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-define-data-source-map">the required API capability "Define a data source for a tile layer"</a>.
<hr>
```

#### Issue [#81](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/81):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#use-case-alternative-layers">the use case "Provide alternative map layers which the user can select"</a>.
<hr>
```
<hr>

#### @nchan0154's

#### Issue [#49](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/49):

```HTML
This issue is for discussion of <a href="https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#tomtom">the reference tool "TomTom Maps SDK for Web"</a>.
<hr>
```

**Comment by NickFitz** [comment]
@Malvoz I've just done mine, including editing the title for a couple of them to match the section they refer to where the wording of that's changed.

Thanks for your work on this!

**Comment by Malvoz** [comment]
@NickFitz 

Thanks!

I had actually missed updating the link for `#74`, I've updated it now, could you redo that one?

**Comment by NickFitz** [comment]
@Malvoz No problem, done :-)

**Comment by nchan0154** [comment]
Done, thank you @Malvoz!

**Comment by prushforth** [comment]
Thank you Robert, you are a great collaborator! Done.

**Comment by prushforth** [comment]
I did @ameliabr's too, cause she's either busy or asleep. I hope that's not bad github etiquette? I was on a roll in an airport lounge...

**Comment by Malvoz** [comment]
Thanks Peter!

Regarding issue https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/21 - I missed to include "Use Case:" in its title, it should rather be:
"_**Use case**: Access additional information about a point on the map_".

And in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/9 you can remove the outdated reference:

> Relevant section: https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#google-maps-embeds-and-google-maps-platform-api
> <hr>

now that you've added the new reference.

Again, thanks, for doing both yours and Amelia's. This is great! Safe travels! 😄

**Comment by AmeliaBR** [comment]
Thanks Peter & Robert!

When I came up with this idea of using GitHub issues for section-by-section discussion, I did not think about all the extra work of keeping them in sync as the document gets re-written and re-organized!

**Comment by Malvoz** [comment]
The example pages have been revamped some time ago, and will need more work but I no longer consider them (or them not linking properly to the spec) "broken", closing this.
