### ISSUE TITLE
Use Cases Todo

### ISSUE THREAD

**Issue by nchan0154** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#205]
The following issues are use cases that need further discussion of details (and potentially capabilities) before they can be included in the report (or dismissed as out of scope)

- Use case (author / website visitor): Require interaction before allowing pan/zoom #180
- Use Case (content author): Include animated spatial data in a layer #182
- Use case (website visitor): Present the map viewer on a remote display #203
- Use case (author / website visitor): Have the map widget adjust to available space responsively #174
- URI scheme to access map data #173
- Use Case: The GeoWeb #172
- Use Case: Handle censored / intentionally vague map data #170
- Requirement: Support Existing Content #169
- Use Case: Side by side / before and after comparisons #167
- Use case (website visitor): View a map in Augmented Reality #135
- Use case: Non-traditional displays #130
- Use Case: Offline maps #123
- Use case (end-user): View a map in fullscreen mode #109
- Use case (end-user): View a map as a Picture-In-Picture media object #107
- Use case (developer): support drag & drop map layers #106
- Use case (end-user): view a map layer as an independent document / in another map viewer #105
- Use Case (website visitor): View your current location on the map, without sharing with the website #75
- Use case (end-user): view a map layer as an independent document / in another map viewer #105
- Use case: View a map in dark mode or high-contrast mode #43
- Use case: search within a set of map features #42
- Use Case: Bookmark/export a location #41
- Use Case: Recover what is drawn on the client by the user as (georeferenced) markup / feature objects #18
- Use case: Geo-referencing HTML content #2

**Comment by Malvoz** [comment]
Closed https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/130 per https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/130#issuecomment-633093198.

**Comment by Malvoz** [comment]
- [x] Rewrote "Use Case: Non-traditional displays" https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/130
- [x] Commented on "Use case (end-user): View a map in fullscreen mode" https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/109
- [x] Commented on "Use case (website visitor): Present the map viewer on a remote display" #203
- [x] Updated comment on "Use case (author / website visitor): Have the map widget adjust to available space responsively" #174
